version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G115
        - G304
    govet:
      enable:
        - asmdecl
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - errorsas
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - stdmethods
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
      enable-all: false
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          arguments:
            - "disable-stuttering-check"
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
