name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    name: Build & Publish Extension Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Precompile and publish release assets
        uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod
